config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index',as: 'home'
  get 'about'=>'pages#about', as: 'about'
  resources :posts

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, 
                    length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title="About Us";
        @content="This is the about Page";
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts=Post.all
    end
    def new
        @post = Post.new
    end

    # buat create
    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)
        if(@post.save)
            redirect_to @post
        else
            render 'new' 
        end
    end
    # ambil id 
    private def post_params
        params.require(:post).permit(:title, :body )
    end

    # get
    def show
        @post = Post.find(params[:id]);
    end

    # buat edit
    def edit
        @post = Post.find(params[:id]);
    end
    def update
        @post = Post.find(params[:id]);
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit' 
        end
    end

    # delete
    def destroy
        @post = Post.find(params[:id]);
        @post.destroy
        redirect_to posts_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  </body>
  <nav class='navbar navbar-expand-lg navbar-light bg-light'>
    <a class='navbar-brand'>My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
      <div class="col l6 s12 collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <%= link_to 'Home', home_path %>
          </li>
        
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
              <%= link_to 'New Post', new_post_path %>
          </li>
        </ul>
    </div>
  </nav>
  <div class='container'>
    <div class='row'>
      <div class='col l6 s12'>
        <%= yield %>
      </div>
    </div>
  </div>
    
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js' %>
  <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js' %>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg|%>
      <div class='alert alert-danger'><%= msg %></div>
      <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class=>'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<br>
    <div class='well'>
        <div class='card' >
            <div class='card-body'>
                <h3 class='card-title'><%= post.title %></h3>
                <div class='card-text'>
                    <p><%= post.body %></p>
                </div>
                <hr>
                <div class='card-text'>
                     <%= link_to 'Read More', post_path(post), :class=>'btn btn default' %>
                </div>
            </div>
        </div>
    </div>
<% end %>
  

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg|%>
      <div class='alert alert-danger'><%= msg %></div>
      <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class=>'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h5><%= @post.title %></h5>
<hr>
<p><%= @post.body %></p>
 <%= link_to 'Edit Post', edit_post_path(@post), :class=>'btn btn default'%>
  <%= link_to 'Delete Post', post_path(@post),
    method: :delete,
    data: {confirm: 'Are you sure?'},
    :class=>'btn btn default'
    %>